Create new readme and add LICENSE
energinet-singularity/file-mover pull request #34
Opened 2022-01-27 13:25 UTC by swedchef

2022-01-28 08:06 UTC, stigsberg requested changes
1 comment have to be fixed in order to have the variable explained more clearly.

2022-01-28 08:06 UTC, stigsberg commented on README.md
> +|CLEAR_INPUT|FALSE|Port of the ksql-server (will be ignored if port is included in KSQL_HOST)|
Describtion to this variable CLEAR_INPUT seems to have a copy/paste error or at least the link between the two is understood by reading it.

2022-01-28 08:06 UTC, stigsberg commented
In the system I have acces to I do not have sudo rights and therefore it have not been tried to spin up the container locally.

2022-01-31 08:59 UTC, swedchef commented on README.md
> +|CLEAR_INPUT|FALSE|Port of the ksql-server (will be ignored if port is included in KSQL_HOST)|
```suggestion
|CLEAR_INPUT|FALSE|If not 'FALSE', files will be deleted after being read in 'input' folder|
```

2022-01-31 09:42 UTC, vjsaini75 approved these changes

2022-01-31 09:43 UTC, vjsaini75 approved these changes

2022-02-01 07:28 UTC, stigsberg approved these changes
LGTM

2022-02-02 07:22 UTC, merged